<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>ArgDefender</PackageId>
    <Title>ArgDefender</Title>
    <Description>Fluent argument validation library that is intuitive and fast.</Description>
    <PackageTags>guard;validation;arguments;fluent</PackageTags>
    <Authors>ftechmax</Authors>
    <Copyright>Copyright (c) 2023-2026 ftechmax</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/ftechmax/argdefender</PackageProjectUrl>
    <RepositoryUrl>https://github.com/ftechmax/argdefender</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSource>true</IncludeSource>
    <PackageOutputPath>../nupkg</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
