name: Pull request build

on:
  merge_group:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - "initial"

jobs:
  build:
    name: Tests
    runs-on: [ubuntu-latest]
    container: mcr.microsoft.com/dotnet/sdk:6.0-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: run dotnet test
        run: dotnet test ./Guard.sln /p:CollectCoverage=true
      
      - name: Upload test and coverage results
        uses: actions/upload-artifact@v3
        with:
          path: ./tests/coverage.json
