name: Pull request

on:
  merge_group:
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Tests
    runs-on: [ubuntu-latest]
    container: mcr.microsoft.com/dotnet/sdk:6.0-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run dotnet test
        run: dotnet test /p:CollectCoverage=true

      - name: Run dotnet pack
        run: dotnet pack ./src/Guard.csproj -c Release
